### ISSUE TITLE
README: Not possible to test with `sam local`?

### ISSUE THREAD

**Issue by swoldemi** [eabglobal/minik#18]
I stumbled upon this repo randomly and apologize if this a trivial matter or outside of scope. Looks promising, but [this](https://github.com/eabglobal/minik/blame/master/README.rst#L98-L100) part of the README put me off a bit. If minik is able to integrate using AWS' SAM, can I not test my functions locally using Docker with [lambci/lambda](https://hub.docker.com/r/lambci/lambda/) and `sam local`? If so, the README should be updated accordingly.

**Comment by pdiazvargas** [comment]
Hey @swoldemi,
You bring up an excellent point, I will be updating the docs to clarify the intent. We were trying to convey the fact that minik does not include a local server. As in a cli command like `minik local` does not exist.
Thanks for the feedback!
